package com.tarea01di.formularios;

import com.tarea01.utilidades.Utilidades;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.io.File;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.help.*;
import java.net.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Juan Carlos Merlos Albarracín
 * @version 1.0.0
 */
public class JDialogGestionAlumnado extends javax.swing.JDialog {

    /**
     * Creates new form JDialogGestionAlumnado
     *
     * @param parent
     * @param modal
     */
    public JDialogGestionAlumnado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            
            // centrado de ventana
            setLocationRelativeTo(null);
            
            //Agrupamos los botones para que sean excluyentes(sólo esté seleccionado uno en un momento).
            buttonGroupModalidad.add(jRadioButtonPresencial);
            buttonGroupModalidad.add(jRadioButtonSemiPresencial);
            buttonGroupModalidad.add(jRadioButtonDistancia);
            
            // estableciendo componentes inciales
            jSpinnerSesiones.setEnabled(false);
            jCheckBoxEquipo.setEnabled(false);
            jComboBoxTipoEquipo.setEnabled(false);
            jComboBoxTipoEquipo.setEnabled(false);
            
            // estableciendo fecha del sistema
            jDateChooserFechaAlta.setDate(new Date());
            
            
            // Cargar el fichero de ayuda
            File fichero = new File("src/help/help_set.hs");
            URL hsURL = fichero.toURI().toURL();
            
            // Crear el HelpSet, instancio la clase HelpSet,
            // pasándole un ClassLoader  la URL del fichero.
            // La calse 'HelpSet' contiene todos los datos relativos a nuestra
            // ayuda leídos de los ficheros de  configuración que hemos creado.
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            
            // Creamos un 'HelpBroker' => clase de ayuda ofrecida por 'JavHelp'
            HelpBroker hb = helpset.createHelpBroker();
            
            /* Asociamos el botón ayuda para que muestre la ayuda.
            // Lo hacemos mediante los métodos 'enableHelpOnButton()
            y enableHelpKey() del HelpBroker'.*/
            
            // Ayuda al hacer click en el JButtonHelp
            hb.enableHelpOnButton(JDialogGestionAlumnado.jButtomHelp, "portada", helpset);
            
            // Ayuda al pulsar F1 sobre la ventana de este formulario,
            // le paso el Formulario en el que estoy
            hb.enableHelp(this.getContentPane(), "vantana_portada", helpset);
        } catch (MalformedURLException | HelpSetException ex) {
            Logger.getLogger(JDialogGestionAlumnado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Método sobreescrito para establecer en la barra de los formularios una
     * imagen o icono
     *
     * @return
     */
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("resources/book.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupModalidad = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabelTelefono1 = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jDateChooserFechaAlta = new com.toedter.calendar.JDateChooser();
        jLabelFechaAlta = new javax.swing.JLabel();
        jLabelModalidad = new javax.swing.JLabel();
        jRadioButtonPresencial = new javax.swing.JRadioButton();
        jRadioButtonDistancia = new javax.swing.JRadioButton();
        jRadioButtonSemiPresencial = new javax.swing.JRadioButton();
        jTextFieldNumHoras = new javax.swing.JTextField();
        jLabelNumHoras = new javax.swing.JLabel();
        jLabelSesiones = new javax.swing.JLabel();
        jSpinnerSesiones = new javax.swing.JSpinner();
        jCheckBoxEquipo = new javax.swing.JCheckBox();
        jLabelHorarioDe = new javax.swing.JLabel();
        jComboBoxHorarioDe = new javax.swing.JComboBox();
        jComboBoxTipoEquipo = new javax.swing.JComboBox();
        jLabelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtomHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tarea01/images/cancel_delete.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("Cancelar operación");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tarea01/images/accept_Check.png"))); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setToolTipText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, new java.awt.Color(102, 102, 102)), "Dartos de contacto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tsukushi A Round Gothic", 1, 14), new java.awt.Color(0, 139, 155))); // NOI18N

        jTextFieldNombre.setToolTipText("Nombre");
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jLabelNombre.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 13)); // NOI18N
        jLabelNombre.setText("   Nombre:");

        jTextFieldApellidos.setToolTipText("Apellidos");
        jTextFieldApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidosActionPerformed(evt);
            }
        });

        jLabelApellidos.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 13)); // NOI18N
        jLabelApellidos.setText("Apellidos:");

        jLabelTelefono.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 13)); // NOI18N
        jLabelTelefono.setText("Teléfono:");

        jTextFieldTelefono.setToolTipText("Teléfono");
        jTextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoActionPerformed(evt);
            }
        });

        jLabelDireccion.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 13)); // NOI18N
        jLabelDireccion.setText("Dirección :");

        jTextFieldDireccion.setToolTipText("Dirección");
        jTextFieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDireccionActionPerformed(evt);
            }
        });

        jLabelTelefono1.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 13)); // NOI18N
        jLabelTelefono1.setText("      D.N.I:");

        jTextFieldDNI.setToolTipText("Teléfono");
        jTextFieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTelefono1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDNI))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelApellidos)
                            .addComponent(jLabelTelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabelDireccion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jTextFieldDireccion))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellidos)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono1)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, null), "Modalidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tsukushi A Round Gothic", 1, 14), new java.awt.Color(0, 139, 155))); // NOI18N

        jDateChooserFechaAlta.setToolTipText("Fecha Alta");

        jLabelFechaAlta.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 13)); // NOI18N
        jLabelFechaAlta.setText("Fecha de alta:");

        jLabelModalidad.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 13)); // NOI18N
        jLabelModalidad.setText("Modalidad:");

        jRadioButtonPresencial.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 13)); // NOI18N
        jRadioButtonPresencial.setSelected(true);
        jRadioButtonPresencial.setText("Presencial");
        jRadioButtonPresencial.setToolTipText("Modalidad Presencial");
        jRadioButtonPresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPresencialActionPerformed(evt);
            }
        });

        jRadioButtonDistancia.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 13)); // NOI18N
        jRadioButtonDistancia.setText("Distancia");
        jRadioButtonDistancia.setToolTipText("Modalidad Distancia");
        jRadioButtonDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDistanciaActionPerformed(evt);
            }
        });

        jRadioButtonSemiPresencial.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 13)); // NOI18N
        jRadioButtonSemiPresencial.setText("Semipresencial");
        jRadioButtonSemiPresencial.setToolTipText("Modalidad Semipresencial");
        jRadioButtonSemiPresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSemiPresencialActionPerformed(evt);
            }
        });

        jTextFieldNumHoras.setToolTipText("Número horas");
        jTextFieldNumHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumHorasActionPerformed(evt);
            }
        });

        jLabelNumHoras.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 13)); // NOI18N
        jLabelNumHoras.setText("Nº de Horas:");

        jLabelSesiones.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 13)); // NOI18N
        jLabelSesiones.setText("Sesiones:");

        jSpinnerSesiones.setModel(new javax.swing.SpinnerNumberModel(0, 0, 8, 1));
        jSpinnerSesiones.setToolTipText("Número sesiones");
        jSpinnerSesiones.setAutoscrolls(true);
        jSpinnerSesiones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinnerSesiones.setEnabled(false);

        jCheckBoxEquipo.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 13)); // NOI18N
        jCheckBoxEquipo.setText("¿Necesita equipo informático?");
        jCheckBoxEquipo.setToolTipText("Marcar si necesita equipo");
        jCheckBoxEquipo.setFocusPainted(false);
        jCheckBoxEquipo.setRequestFocusEnabled(false);
        jCheckBoxEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEquipoActionPerformed(evt);
            }
        });

        jLabelHorarioDe.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 13)); // NOI18N
        jLabelHorarioDe.setText("  Horario de:");

        jComboBoxHorarioDe.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jComboBoxHorarioDe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "Mañana ", "Tarde ", "A distancia" }));
        jComboBoxHorarioDe.setToolTipText("Horario (Turno)");

        jComboBoxTipoEquipo.setFont(new java.awt.Font("Sukhumvit Set", 0, 13)); // NOI18N
        jComboBoxTipoEquipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sobremesa ", "Portátil" }));
        jComboBoxTipoEquipo.setToolTipText("Tipo equipo");
        jComboBoxTipoEquipo.setEnabled(false);
        jComboBoxTipoEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFechaAlta)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHorarioDe)
                            .addComponent(jLabelNumHoras))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserFechaAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNumHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxHorarioDe, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabelModalidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPresencial)
                .addGap(19, 19, 19)
                .addComponent(jRadioButtonDistancia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonSemiPresencial)
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabelSesiones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jCheckBoxEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(486, 486, 486)
                .addComponent(jComboBoxTipoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelFechaAlta)
                    .addComponent(jDateChooserFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelModalidad)
                    .addComponent(jRadioButtonPresencial)
                    .addComponent(jRadioButtonDistancia)
                    .addComponent(jRadioButtonSemiPresencial))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumHoras)
                    .addComponent(jTextFieldNumHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSesiones)
                    .addComponent(jSpinnerSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxEquipo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxHorarioDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelHorarioDe))
                    .addComponent(jComboBoxTipoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabelTitulo.setFont(new java.awt.Font("Tsukushi A Round Gothic", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 139, 155));
        jLabelTitulo.setText("GESTIÓN DEL ALUMNADO");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tarea01/images/book.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tarea01/images/Out-icon.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.setToolTipText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtomHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tarea01/images/help_64x64.jpg"))); // NOI18N
        jButtomHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtomHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAceptar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtomHelp))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButtonAceptar, jButtonCancelar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtomHelp)
                                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButton1))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButtonAceptar, jButtonCancelar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        // inicializando campos
        jTextFieldApellidos.setText("");
        jTextFieldNombre.setText("");
        jTextFieldTelefono.setText("");
        jTextFieldDNI.setText("");
        jTextFieldDireccion.setText("");
        jDateChooserFechaAlta.setToolTipText("");
        jTextFieldNumHoras.setText("");

        jSpinnerSesiones.setEnabled(false);
        jCheckBoxEquipo.setEnabled(false);
        jComboBoxTipoEquipo.setEnabled(false);
        jComboBoxTipoEquipo.setEnabled(false);
        jRadioButtonPresencial.setSelected(false);

        buttonGroupModalidad.clearSelection();

        // estableciendo fecha del sistema
        jDateChooserFechaAlta.setDate(new Date());

        jDateChooserFechaAlta.setDate(new Date());
        jComboBoxHorarioDe.setSelectedIndex(0);
        jSpinnerSesiones.setValue(0);

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed

        /**
         * ************* validando campos antes de guardar *******************
         */
        // validando que el campo apellidos no esté vacío y no supere los 25 caracteres
        if (jTextFieldApellidos.getText().equals("") || jTextFieldApellidos.getText().length() > 50) {
            JOptionPane.showMessageDialog(rootPane,
                    "Debe introducir unos apellidos y no superar los 50 caracteres");
            jTextFieldApellidos.setText("");
            jTextFieldApellidos.requestFocusInWindow();
            return;
        }

        // validando que el campo nombre no esté vacío y no supere los 50 caracteres
        if (jTextFieldNombre.getText().equals("") || jTextFieldNombre.getText().length() > 25) {
            JOptionPane.showMessageDialog(rootPane,
                    "Debe introducir un nombre y no superar los 25 caracteres");
            jTextFieldNombre.setText("");
            jTextFieldNombre.requestFocusInWindow();
            return;
        }

        // validando que teléfono contenga valor numérico
        if (!Utilidades.compruebaTelefono(jTextFieldTelefono.getText())
                || jTextFieldTelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane,
                    "Debe introducir un número de teléfono válido de nueve cifras."
                    + "Debe empezar por 6,7,8 ó 9  y el campo no debe estar vacio");
            jTextFieldTelefono.setText("");
            jTextFieldTelefono.requestFocusInWindow();
            return;
        }

        // Validar que es un NIF o NIE correcto
        if (!Utilidades.validarNifONie(jTextFieldDNI.getText()) || jTextFieldDNI.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                    "El DNI o NIE introducido no es válido o el campo esta vacio");
            jTextFieldDNI.setText("");
            jTextFieldDNI.requestFocusInWindow();
            return;
        }

        // validando que el campo dirección no esté vacío
        if (jTextFieldDireccion.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe introducir una dirección");
            jTextFieldDireccion.setText("");
            jTextFieldDireccion.requestFocusInWindow();
            return;
        }

        // validando que el número de horas contenga valor numérico
        if (!Utilidades.isNumeric(jTextFieldNumHoras.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Debe introducir un valor "
                    + "númerico para el número de horas");
            jTextFieldNumHoras.setText("");
            jTextFieldNumHoras.requestFocusInWindow();
            return;
        }
        // guardo el número de horas y las parseo a tipo float
        float numHoras = Float.parseFloat(jTextFieldNumHoras.getText());

        // comprobando el número máximo de horas en modalidad Presencial
        if (jRadioButtonPresencial.isSelected() == true && numHoras > 2000) {
            JOptionPane.showMessageDialog(rootPane,
                    "El número de horas en la modalidad Presencial  "
                    + "no puede ser superior a 2000 horas");
            jTextFieldNumHoras.setText("");
            jTextFieldNumHoras.requestFocusInWindow();
            jRadioButtonDistancia.requestFocusInWindow();
            return;
        }

        // Comprobando el número de horas en la modalidad semipresencial
        if (jRadioButtonSemiPresencial.isSelected() == true && numHoras > 2000) {
            JOptionPane.showMessageDialog(rootPane,
                    "El número de horas en la modalidad Semipresencial "
                    + "no puede ser superior a 2000 horas");
            jTextFieldNumHoras.setText("");
            jTextFieldNumHoras.requestFocusInWindow();
            return;
        }

        // comprobando el número de horas en la modalidad a Distancia
        if (jRadioButtonDistancia.isSelected() == true && numHoras > 1000) {
            JOptionPane.showMessageDialog(rootPane,
                    "El número de horas en la modalidad a Distancia "
                    + "no puede ser superior a 1000 horas");
            jTextFieldNumHoras.setText("");
            jTextFieldNumHoras.requestFocusInWindow();
            return;
        }

        // comprobando que se ha seleccionado el horario
        if (jComboBoxHorarioDe.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "Seleccione el horario para la modalidad elegida");
            jComboBoxHorarioDe.setSelectedIndex(0);
            jComboBoxHorarioDe.requestFocusInWindow();
            return;
        }

        // comprobando que se ha elegido el número de sesiones si la modalidad es Semipresencial
        if (jRadioButtonSemiPresencial.isSelected() && jSpinnerSesiones.getValue().equals(0)) {
            JOptionPane.showMessageDialog(rootPane,
                    "Debe seleccionar el número de sesiones");
            jSpinnerSesiones.setValue(0);
            jSpinnerSesiones.requestFocusInWindow();
            return;
        }

        // mensaje de Ok
        JOptionPane.showMessageDialog(rootPane, "El registro ha sido guardado con éxito");

        // incializando campos
        jTextFieldApellidos.setText("");
        jTextFieldNombre.setText("");
        jTextFieldTelefono.setText("");
        jTextFieldDNI.setText("");
        jTextFieldDireccion.setText("");
        jDateChooserFechaAlta.setToolTipText("");
        jTextFieldNumHoras.setText("");

        jSpinnerSesiones.setEnabled(false);
        jCheckBoxEquipo.setEnabled(false);
        jComboBoxTipoEquipo.setEnabled(false);
        jComboBoxTipoEquipo.setEnabled(false);
        jRadioButtonPresencial.setSelected(true);

        buttonGroupModalidad.clearSelection();

        // estableciendo fecha del sistema
        jDateChooserFechaAlta.setDate(new Date());

        jDateChooserFechaAlta.setDate(new Date());
        jComboBoxHorarioDe.setSelectedIndex(0);
        jSpinnerSesiones.setValue(0);

    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidosActionPerformed

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed

        if (!Utilidades.isNumeric(jTextFieldTelefono.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Debe introducir un número válido,"
                    + " no puede contener letras");
            jTextFieldTelefono.setText("");
            jTextFieldTelefono.requestFocusInWindow();
        }
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDireccionActionPerformed

    private void jRadioButtonPresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPresencialActionPerformed

        if (jRadioButtonSemiPresencial.isEnabled()) {
            jSpinnerSesiones.setEnabled(false);
            jCheckBoxEquipo.setSelected(false);
            jCheckBoxEquipo.setEnabled(false);
            jComboBoxTipoEquipo.setEnabled(false);
            jSpinnerSesiones.setValue(0);
        }
    }//GEN-LAST:event_jRadioButtonPresencialActionPerformed

    private void jRadioButtonDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDistanciaActionPerformed

        if (jRadioButtonSemiPresencial.isEnabled()) {
            jSpinnerSesiones.setEnabled(false);
            jCheckBoxEquipo.setSelected(false);
            jCheckBoxEquipo.setEnabled(false);
            jComboBoxTipoEquipo.setEnabled(false);
            jSpinnerSesiones.setValue(0);
        }
    }//GEN-LAST:event_jRadioButtonDistanciaActionPerformed

    private void jRadioButtonSemiPresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSemiPresencialActionPerformed

        if (jRadioButtonSemiPresencial.isSelected()) {
            jSpinnerSesiones.setEnabled(true);
            jCheckBoxEquipo.setEnabled(true);
            jComboBoxTipoEquipo.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButtonSemiPresencialActionPerformed

    private void jTextFieldNumHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumHorasActionPerformed

    }//GEN-LAST:event_jTextFieldNumHorasActionPerformed

    private void jCheckBoxEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEquipoActionPerformed

        jCheckBoxEquipo.addItemListener((ItemEvent e) -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                jComboBoxTipoEquipo.setEnabled(jCheckBoxEquipo.isSelected());
            } else {
                jComboBoxTipoEquipo.setEnabled(false);
            }
        });
    }//GEN-LAST:event_jCheckBoxEquipoActionPerformed

    private void jComboBoxTipoEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoEquipoActionPerformed

        if (!jCheckBoxEquipo.isEnabled()) {
            jComboBoxTipoEquipo.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxTipoEquipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDNIActionPerformed

    private void jButtomHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtomHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtomHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogGestionAlumnado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogGestionAlumnado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogGestionAlumnado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogGestionAlumnado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JDialogGestionAlumnado dialog = new JDialogGestionAlumnado(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
            
            try {
//                    // Cargar el fichero de ayuda
//                    File fichero = new File("/Users/macbookpro/Documents/GRADO/DI/TAREAS_DI/TAREA04_DI/"
//                            + "merlos_albarracin_juan_carlos_DI04_Tarea_E1/build/classes/help/help_set.hs");
//                    URL hsURL = fichero.toURI().toURL();
//
//                    // Crear el HelpSet, instancio la clase HelpSet, 
//                    // pasándole un ClassLoader  la URL del fichero.
//                    // La calse 'HelpSet' contiene todos los datos relativos a nuestra 
//                    // ayuda leídos de los ficheros de  configuración que hemos creado.
//                    HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
//
//                    // Creamos un 'HelpBroker' => clase de ayuda ofrecida por 'JavHelp'
//                    HelpBroker hb = helpset.createHelpBroker();
//
//                    /* Asociamos el botón ayuda para que muestre la ayuda.
//                     // Lo hacemos mediante los métodos 'enableHelpOnButton() 
//                     y enableHelpKey() del HelpBroker'.*/
//                    
//                    // Ayuda al Ayuda al hacer click en el JButtonHelp
//                    hb.enableHelpOnButton(JDialogGestionAlumnado.jButtomHelp, "portada", helpset);
//
//                    // Ayuda al pulsar F1 sobre la ventana de este formulario, 
//                    // le paso el Formulario en el que estoy
//                    hb.enableHelp(dialog.getContentPane(), "vantana_portada", helpset);
                
                
                
                
                
                
                
//                URL hsURL = HelpSet.findHelpSet(null, "/help.hs");
//                HelpSet hs = new HelpSet(null, hsURL);
//                HelpBroker hb = hs.createHelpBroker();
//                hb.enableHelpOnButton(JDialogGestionAlumnado.jButtomHelp, "Introducción", hs);
//                // Asociar ayuda botón F1
//                hb.enableHelpKey(SwingUtilities.getRootPane(dialog), "Introducción", hs);
//                // Asociar componente a una página que se muestre al pulsar la tecla de ayuda F1
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(null, "Fichero HelpSet no encontrado, error: "
                        + Arrays.toString(e.getStackTrace()));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupModalidad;
    private static javax.swing.JButton jButtomHelp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JCheckBox jCheckBoxEquipo;
    private javax.swing.JComboBox jComboBoxHorarioDe;
    private javax.swing.JComboBox jComboBoxTipoEquipo;
    private com.toedter.calendar.JDateChooser jDateChooserFechaAlta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelFechaAlta;
    private javax.swing.JLabel jLabelHorarioDe;
    private javax.swing.JLabel jLabelModalidad;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumHoras;
    private javax.swing.JLabel jLabelSesiones;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTelefono1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButtonDistancia;
    private javax.swing.JRadioButton jRadioButtonPresencial;
    private javax.swing.JRadioButton jRadioButtonSemiPresencial;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerSesiones;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumHoras;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
